import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/navigation/Sidebar";

export const metadata: Metadata = {
  title: "Portfolio - Adrian Birta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex">
        <header>
          <Sidebar />
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
