import type { Metadata } from "next";
import "./globals.css";
import HashRedirect from "@/lib/HashRedirect";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Portfolio - Adrian Birta",
  description: "Generated by create next app",
  icons: "/images/iconM16.webp"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-137G9GGKST"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-137G9GGKST');
          `}
        </Script>
      </head>
      <body className="h-screen m-0 p-0 min-h-80">
        <HashRedirect />
        <main className="h-screen m-0 p-0 min-h-80">
          {children}
        </main>
      </body>
    </html>
  );
}
